### ISSUE TITLE
verify_upgrade_path is failing with 'edges_correlation'' is undefined

### ISSUE THREAD

**Issue by X-dark** [Secsec/openshift_upgrade_checks#4]
I have a cluster running OCP 4.9.23. I target `4.10.18` on channel `stable-4.10`. According to [1] a direct update path does exists.

When I run the playbook, I get the following error:

```
TASK [role_upgrade_check : Retrieve the version based on the previous edge correlation] ***********************************************
fatal: [aws-emea-unfiltered]: FAILED! => 
  msg: '''edges_correlation'' is undefined'
```
Verbose output is here [2]

[1] https://access.redhat.com/labs/ocpupgradegraph/update_path?channel=stable-4.10&arch=x86_64&is_show_hot_fix=false&current_ocp_version=4.9.23&target_ocp_version=4.10.18
[2] https://gist.github.com/X-dark/1340d0b4a46bd742a846a8b8cdd97520

**Comment by Secsec** [comment]
Hi,

Just ran with the same inputs as yours and got that:
TASK [role_upgrade_check : debug] ***************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "4.10.10",
        "4.10.11",
        "4.10.12",
        "4.10.13",
        "4.10.14",
        "4.10.15",
        "4.10.16",
        "4.10.17",
        "4.10.18",
        "4.10.20",
        "4.10.3",
        "4.10.4",
        "4.10.5",
        "4.10.6",
        "4.10.8",
        "4.10.9",
        "4.9.24",
        "4.9.25",
        "4.9.26",
        "4.9.27",
        "4.9.28",
        "4.9.29",
        "4.9.31",
        "4.9.32",
        "4.9.33",
        "4.9.35",
        "4.9.36",
        "4.9.37"
    ]
    
    could you please share the defaut.yml values that you provided?

**Comment by X-dark** [comment]
I ran it again since 4.10.20 appearance in stable and this is now ok:

```yaml
TASK [role_upgrade_check : Retrieve the version based on the previous edge correlation] *****************************************************************************************************************************************************************************************
ok: [aws-emea-unfiltered] => (item=9) => changed=false 
  ansible_facts:
    version_path:
    - 4.10.20
  ansible_loop_var: item
  item: 9

TASK [role_upgrade_check : debug] ***********************************************************************************************************************************************************************************************************************************************
ok: [aws-emea-unfiltered] => 
  msg:
  - 4.10.20
 ```

But I don't understand the output as I provided:

```ini
role_upgrade_channel_name=stable-4.10                                           
role_upgrade_channel_version=4.10.18
```

Or do I misunderstand the purpose of role_upgrade_channel_version?
